In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("placement.csv")

In [3]:
# how big is the data
df.shape

(100, 4)

In [6]:
# how does it look/preview
# df.head()
df.sample(5)

    Unnamed: 0  cgpa     iq  placement
32          32   7.0  139.0          1
14          14   6.1  103.0          0
96          96   4.4   42.0          0
42          42   7.6   89.0          1
46          46   5.3  114.0          0

In [7]:
# datatypes of columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.2 KB

In [8]:
# check total missing values
df.isnull().sum()

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64

In [9]:
# how data statistically look
df.describe()

       Unnamed: 0        cgpa          iq   placement
count  100.000000  100.000000  100.000000  100.000000
mean    49.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      0.000000    3.300000   37.000000    0.000000
25%     24.750000    5.075000  101.500000    0.000000
50%     49.500000    6.000000  127.500000    0.500000
75%     74.250000    6.900000  149.000000    1.000000
max     99.000000    8.500000  233.000000    1.000000

In [10]:
# total duplicate values
df.duplicated().sum()

np.int64(0)

In [11]:
# correlation between columns
df.corr()

            Unnamed: 0      cgpa        iq  placement
Unnamed: 0    1.000000  0.047478 -0.019080   0.144807
cgpa          0.047478  1.000000 -0.098791   0.821688
iq           -0.019080 -0.098791  1.000000  -0.083031
placement     0.144807  0.821688 -0.083031   1.000000