In [51]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(r"C:\Users\SHILA\OneDrive\Desktop\PYTHON\ML_practiceDays\Datasets\cars.csv")
df.sample(5)

          brand  km_driven    fuel         owner  selling_price
3677   Mahindra      73000  Diesel   First Owner         670000
6072   Mahindra     110000  Diesel   First Owner         250000
7134  Chevrolet      70000  Petrol   Third Owner         148000
1826   Mahindra     103000  Diesel   First Owner         550000
444      Maruti      70000  Petrol  Second Owner         120000

In [53]:
df['brand'].value_counts() # each category total values

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [54]:
df['brand'].nunique() # total n number of unique categories

32

In [55]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [56]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [57]:
# OneHotEncoding using pandas, temporary type
pd.get_dummies(df,columns=['fuel','owner'], drop_first=True) # datset, columns on which OneHotEncoding applied, drop first column of each encoded form as in OneHotEncoding

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [58]:
# OneHeadEncoding in sklearn
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest=train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=0)

In [59]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [60]:
xtrain_new=ohe.fit_transform(xtrain[['fuel', 'owner']])

In [61]:
xtest_new=ohe.fit_transform(xtest[['fuel','owner']])

In [62]:
np.hstack((xtrain[['brand','km_driven']].values,xtrain_new)).shape

(6502, 9)

In [63]:
xtrain_new.shape

(6502, 7)

In [65]:
# working on brand column
counts=df['brand'].value_counts()

In [66]:
df['brand'].nunique()
threshold=100

In [67]:
repl=counts[counts<=threshold].index

In [70]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3813,0,0,0,0,0,0,1,0,0,0,0,0,0
7103,0,0,0,0,0,0,1,0,0,0,0,0,0
787,0,0,0,0,0,1,0,0,0,0,0,0,0
2148,0,0,0,0,0,0,1,0,0,0,0,0,0
4169,0,0,0,0,0,0,1,0,0,0,0,0,0